appsquickly/typhoon

- Source/Factory/Block/TyphoonAssemblyDefinitionBuilder.m
The last update to LLVM made it necesary to cast objc_msgSend to the
desired type before using it (it takes no arguments in it's definition).
This in combination with changed build settings in CocoaPods 0.36 beta
caused Typhoon not to compile.
> Cast the call to objc_msgSend to the adequate type

- Source/Utils/TyphoonIntrospectionUtils.m
If there is a space in the Product Name (CFBundleName),
NSClassFromString will not find the class. Need to convert the “ “ to
“_” for the defaultModuleName before calling NSClassFromString.
> Bug fix getting Class from ClassName with spaces in Bundle Name

- Source/Configuration/ConfigPostProcessor/TyphoonConfigPostProcessor.m
- Source/Configuration/TyphoonAbstractDetachableComponentFactoryPostProcessor.m
- Source/Configuration/TyphoonDefinitionPostProcessor.h
- Source/Definition/AutoInjection/TyphoonFactoryAutoInjectionPostProcessor.m
- Source/Factory/Internal/TyphoonFactoryPropertyInjectionPostProcessor.m
- Source/Factory/Internal/TyphoonParentReferenceHydratingPostProcessor.m
- Source/Factory/TyphoonComponentFactory.m
- Source/Utils/TyphoonIntrospectionUtils.h
- Source/Utils/TyphoonIntrospectionUtils.m
- Source/ios/Configuration/Resolver/TyphoonViewControllerNibResolver.m
- Tests/Configuration/TyphoonComponentFactoryPostProcessorStubImpl.m
I described my solution here: #325
> Fix slow [factory registerDefinition:] method.

- Source/Definition/AutoInjection/TyphoonFactoryAutoInjectionPostProcessor.m
- Source/Utils/TyphoonIntrospectionUtils.m
- Typhoon.xcodeproj/xcshareddata/xcschemes/TyphoonFrameworkSwiftExample.xcscheme
- Typhoon.xcodeproj/xcshareddata/xcschemes/TyphoonSwift.xcscheme
Infinite loop in some while-loops produced when we have a class that don't share the same vertical, object-oriented inheritance. In my case is produced when I try to introspect NSProxy class.
Right know the loop is broken when a root class (aka "clazz = Nil") is detected.
I make a workaround on the affected classes but of course I don't know all the scope of the project. Just let me know your thoughts!
> Inifinite loop in some while-loops

- Source/Factory/Assembly/TyphoonAssembly.m
objc_msgSend properly casted to new style. The old style causes compile errors.
> New casting objc_msgSend

- Source/ios/Storyboard/TyphoonStoryboard.h
- Source/ios/Storyboard/TyphoonStoryboard.m
This should make it easier to use this class from Swift making it
possible to pass assemblies to class constructor without casting.
> Make TyphoonStoryboard accept id<TyphoonComponentFactory> instead of TyphoonComponentFactory

- Source/Configuration/ConfigPostProcessor/TyphoonConfigPostProcessor.h
- Source/Configuration/ConfigPostProcessor/TyphoonConfigPostProcessor.m
- Source/Definition/Internal/TyphoonDefinition+Infrastructure.h
- Source/Definition/Internal/TyphoonDefinition+Infrastructure.m
Added the *+configDefinitionWithName:bundle:* method
> Fixed the issue #348

- Source/ios/Storyboard/TyphoonStoryboard.m
My usecase for this was a large UIView subclass with some distinct pieces of logic.  I felt that it was violating SRP, so I extracted the logic into a couple of classes.   I needed some way to inject the new class dependencies into the UIView subclass.
> Inject dependencies into storyboard views that have a typhoonKey

- Source/Utils/TyphoonIntrospectionUtils.m
The module name replaces dashes in the bundle name with an underscore, so the code to calculate the defaultModuleName needs to replace a dash as well as a space with an underscore.
This is necessary for targets or bundles that have dash in the same, which specifically in my project's case is the `-cal` target used by Calabash.
> Support bundle names that have a dash in them

- Typhoon.xcodeproj/xcshareddata/xcschemes/Typhoon.xcscheme
Fixing scheme so it builds a framework.
This is basically reverting the changes to Typhoon.xcscheme made in b00dd8161eb2ebb34a325be08cb69111075d0215. 
Verified that it builds with carthage.
> Fixing framework not building.

- Typhoon.xcodeproj/project.pbxproj
To test the Carthage built framework you can use this in a Cartfile:
```
github "akiraspeirs/Typhoon" "fix-public-headers"
```
I still get the following warnings after adding the framework, but I think they were present before (at least they were at 3.1.8):
```
<module-includes>:1:1: Umbrella header for module 'Typhoon' does not include header 'OCLogTemplate.h'
<module-includes>:1:1: Umbrella header for module 'Typhoon' does not include header 'TyphoonInstancePostProcessor.h'
```
I've checked that it builds correctly when included in a new project.
> Adding TyphoonFactoryDefinition to public headers

- Source/Definition/Injections/TyphoonInjectionByComponentFactory.m
- Tests/Definition/Injection Aware/ComponentFactoryAwareAssembly.h
- Tests/Definition/Injection Aware/ComponentFactoryAwareAssembly.m
- Tests/Definition/Injection Aware/TyphoonComponentFactoryAwareTests.m
Added a quick-fix for injection by component factory mechanism. Now, when you call *[definition injectProperty:@selector(assembly) with:self];*, the concrete subclass of *TyphoonAssembly* backed by *TyphoonComponentFactory* is injected.
It fixes the problems with performing class and protocol checks on injected assembly.
Though we still need the better solution.
> Assembly injection fix

- Source/Configuration/Startup/TyphoonStartup.m
- Source/Factory/Internal/TyphoonAssemblyBuilder+PlistProcessor.h
- Source/Factory/Internal/TyphoonAssemblyBuilder+PlistProcessor.m
- Source/Factory/Internal/TyphoonAssemblyBuilder.h
- Source/Factory/Internal/TyphoonAssemblyBuilder.m
- Source/Factory/Internal/TyphoonBlockComponentFactory.h
- Source/Factory/Internal/TyphoonBlockComponentFactory.m
- Tests/Factory/Assembly/TyphoonAssemblyBuilderTests.m
- Typhoon.xcodeproj/project.pbxproj
I've added the new way of activating assemblies on the application start up:
```
@implementation AppDelegate
- (NSArray *)initialAssemblies
{
return @[[Assembly1 class], [Assembly2 class]];
}
@end
```
That can help when you have too many assemblies to include all of them into the `Info.plist` file, and don't want to manually create `TyphoonBlockComponentFactory` with the `-initialFactory` method.
I have only one doubt - in the `TyphoonStartup.m`, in the method `+factoryFromAppDelegate:`, I have to use the `-performSelector:` method and surround it with `#pragma clang diagnostic` messages. Can you suggest a better way (maybe adding a special protocol for the `AppDelegate`)?
> Providing initial assemblies classes in the AppDelegate

- Source/TypeConversion/TyphoonTypeDescriptor.m
- Source/Utils/TyphoonIntrospectionUtils.m
Hey folks!
We are using Typhoon extensively in our application (works like a charm, thanks!). However, recent tests on older devices (4S) showed that Typhoon took quite a lot of time on startup, delaying the launch of application. It turns out that most of this time can be cut down with a couple of minor fixes.
The first thing taking a whole lot of time happens in `TyphoonClassFromString`. It turns out that `[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleExecutable"];` is a very expensive thing to do. However, we can avoid going to this fallback branch entirely by checking if `className` is 100% invalid. Two simple cases currently covered are no class name specified at all (aka empty string) and block (aka question mark). There might be more, though this was sufficient for my …
> Improve introspection performance

- Source/Factory/Assembly/TyphoonAssembly.m
- Source/Factory/TyphoonComponentFactory.h
- Tests/Definition/TyphoonDefinitionTests.m
- Tests/Factory/Assembly/TyphoonAssemblyTests.m
- Tests/Factory/TyphoonComponentFactoryTests.m
- Tests/Factory/WeakPool/TyphoonWeakComponentsPoolTests.m
- Tests/Startup/TyphoonAppDelegateWithBothMethodsMock.h
- Tests/Startup/TyphoonAppDelegateWithBothMethodsMock.m
- Tests/Startup/TyphoonAppDelegateWithInitialAssembliesMock.h
- Tests/Startup/TyphoonAppDelegateWithInitialAssembliesMock.m
- Tests/Startup/TyphoonAppDelegateWithInitialFactoryMock.h
- Tests/Startup/TyphoonAppDelegateWithInitialFactoryMock.m
- Tests/Startup/TyphoonStartupTests.m
- Tests/Startup/TyphoonStartup_Testable.h
- Tests/Utils/TyphoonSwizzlerTests.m
- Typhoon.xcodeproj/project.pbxproj
Besides some unit tests, fixed the ability to use object subscription syntax with `TyphoonComponentFactory` and `TyphoonAssembly`:
```objc
_factory[@"knight"];
_assembly[[Knight class]];
```
> Increased the percent of code coverage (up to 88.3)

- Typhoon.xcodeproj/project.pbxproj
- build.sh
Issue: https://github.com/appsquickly/Typhoon/issues/411
Typhoon.framework target is broken because TyphoonInjectionDefinition is missing from the framework target. 
This PR adds this class to the target. 
I also extended the build.sh to build Typhoon.framework as well so these kind of issues will surface quickly.
> Fix Typhoon.framework target

- Source/ios/Storyboard/TyphoonStoryboardProvider.h
- Source/ios/Storyboard/TyphoonStoryboardProvider.m
- Source/ios/Storyboard/TyphoonStoryboardResolver.h
- Source/ios/Storyboard/TyphoonStoryboardResolver.m
- Tests/iOS/StoryboardProvider/TyphoonStoryboardProviderTests.m
- Typhoon.xcodeproj/project.pbxproj
As discussed in Issue #415, I've added the automated activation of all of the storyboards in the main bundle of the application. If a user doesn't want to activate any of the storyboards, he can list it under the `TyphoonCleanStoryboards` key in the `Info.plist` file.
I've tested the behaviour with the referenced storyboards feature - everything is working. Unfortunately I had to remove this test, because to support it we'd have to increase the Deployment Target up to 9.0.
After merging I'll add the corresponding information to the wiki.
> Multiple storyboards support

- Source/Factory/Internal/TyphoonAssemblyAdviser.h
Hi all,
Just a tiny one - currently trying to build our project with dynamic frameworks, and importing the umbrella header for Cocoapods. Small error here because `class` is used as a method parameter, and C++ isn't as tolerant of this an ObjC.
Thanks!
> Remove use of reserved keyboard in public header

- Source/Utils/TyphoonIntrospectionUtils.m
Iterating over [NSBundle allFrameworks] every time is expensive, so this should ease the pain.
> TyphoonClassFromString performance optimization

- Source/Definition/Injections/TyphoonInjectionByObjectFromString.m
- Source/Factory/TyphoonComponentFactory.h
- Source/Factory/TyphoonComponentFactory.m
- Source/Factory/TyphoonDefinitionRegisterer.m
- Source/TypeConversion/Converters/TyphoonNSNumberTypeConverter.m
- Source/TypeConversion/Converters/TyphoonNSURLTypeConverter.m
- Source/TypeConversion/Converters/TyphoonPassThroughTypeConverter.m
- Source/TypeConversion/Converters/TyphoonPrimitiveTypeConverter.h
- Source/TypeConversion/Helpers/TyphoonColorConversionUtils.h
- Source/TypeConversion/Helpers/TyphoonColorConversionUtils.m
- Source/TypeConversion/TyphoonTypeConversionUtils.h
- Source/TypeConversion/TyphoonTypeConversionUtils.m
- Source/TypeConversion/TyphoonTypeConverter.h
- Source/TypeConversion/TyphoonTypeConverterRegistry.h
- Source/TypeConversion/TyphoonTypeConverterRegistry.m
- Source/ios/TypeConversion/Converters/TyphoonBundledImageTypeConverter.m
- Source/ios/TypeConversion/Converters/TyphoonUIColorTypeConverter.m
- Source/osx/TypeConversion/Converters/TyphoonNSColorTypeConverter.h
- Source/osx/TypeConversion/Converters/TyphoonNSColorTypeConverter.m
- Tests/Factory/Internal/TyphoonBlockComponentFactoryTests.m
- Tests/OSX/TypeConversion/TyphoonNSColorTypeConverterTests.m
- Tests/TypeConversion/TyphoonNSNumberTypeConverterTests.m
- Tests/TypeConversion/TyphoonPassthroughTypeConverterTests.m
- Tests/TypeConversion/TyphoonTypeConversionUtilsTests.m
- Tests/TypeConversion/TyphoonTypeConverterRegistryTests.m
- Tests/iOS/TypeConversion/TyphoonUIColorConverterTests.m
- Typhoon.xcodeproj/project.pbxproj
This PR fixes the Issue #407. `TyphoonTypeConverterRegistry` is now not a shared variable, but relates to `TyphoonComponentFactory`.
Besides it, I've added a couple of new unit tests and a `TyphoonNSColorTypeConverter`, as an OSX opposite of `TyphoonUIColorTypeConverter`.
> Removed the singletone TyphoonTypeConverterRegistry

- Source/Configuration/Startup/TyphoonStartup.m
- Source/Factory/Assembly/TyphoonAssembly+TyphoonAssemblyFriend.h
- Source/Factory/Assembly/TyphoonAssembly.m
- Source/Factory/Internal/TyphoonBlockComponentFactory.m
- Source/Factory/Internal/TyphoonComponentFactory+TyphoonDefinitionRegisterer.h
- Source/Factory/TyphoonComponentFactory.h
- Source/Factory/TyphoonComponentFactory.m
- Source/Factory/TyphoonDefinitionRegisterer.m
- Source/Factory/TyphoonPreattachedComponentsRegisterer.h
- Source/Factory/TyphoonPreattachedComponentsRegisterer.m
- Tests/Factory/Assembly/TyphoonAssemblyTests.m
- Tests/Factory/Internal/TyphoonBlockComponentFactoryTests.m
- Tests/Factory/TyphoonComponentFactoryTests.m
- Tests/Test/Patcher/TyphoonPatcherTests.m
- Typhoon.xcodeproj/project.pbxproj
This PR relates to issue #344. The user can now pre-attach infrastructure components to the non-activated assembly. These components are:
- `TyphoonDefinitionPostProcessor's`
- `TyphoonInstancePostProcessors`
- `TyphoonTypeConverters`
When the assembly will be activated these components would be attached to the underlying `TyphoonComponentFactory`.
The following methods are deprecated:
- `[TyphoonComponentFactory attachPostProcessor]`
- `[TyphoonComponentFactory addInstancePostProcessor]`
> Preattaching infrastructure components

- Source/Configuration/ConfigPostProcessor/TyphoonConfigPostProcessor.h
- Source/Configuration/ConfigPostProcessor/TyphoonConfigPostProcessor.m
- Source/Configuration/GlobalConfigResolver/TyphoonGlobalConfigCollector.h
- Source/Configuration/GlobalConfigResolver/TyphoonGlobalConfigCollector.m
- Source/Configuration/Startup/TyphoonStartup.m
- Source/Definition/Injections/TyphoonInjectionByConfig.m
- Source/Definition/Internal/TyphoonDefinition+Infrastructure.h
- Source/Definition/Internal/TyphoonDefinition+Infrastructure.m
- Source/Definition/Namespacing/TyphoonDefinition+Namespacing.h
- Source/Definition/Namespacing/TyphoonDefinition+Namespacing.m
- Source/Definition/Namespacing/TyphoonDefinitionNamespace.h
- Source/Definition/Namespacing/TyphoonDefinitionNamespace.m
- Source/Definition/TyphoonDefinition.h
- Source/Factory/Internal/TyphoonAssemblyDefinitionBuilder.m
- Source/Factory/Internal/TyphoonComponentFactory+InstanceBuilder.m
- Source/Factory/TyphoonDefinitionRegisterer.m
- Tests/Configuration/TyphoonConfigAppDelegateMock.h
- Tests/Configuration/TyphoonConfigAppDelegateMock.m
- Tests/Configuration/TyphoonConfigPostProcessorTests.m
- Tests/Configuration/TyphoonGlobalConfigCollectorTests.m
- Tests/Configuration/TyphoonTestAssemblyConfigPostProcessor.h
- Tests/Configuration/TyphoonTestAssemblyConfigPostProcessor.m
- Tests/Factory/Assembly/TestAssemblies/Config/ConfigAssembly.m
- Tests/Factory/TyphoonNamespacingTests.m
- Tests/Resources/PropertiesA.plist
- Tests/Resources/PropertiesB.plist
- Typhoon.xcodeproj/project.pbxproj
This PR introduces namespacing for `TyphoonDefinitions` and `TyphoonConfigPostProcessors` (Issue #263).
There are two types of namespaces (`TyphoonDefinitionNamespace`):
- A global namespace,
- A namespace with the key equal to `TyphoonDefinition` assembly name.
Currently `TyphoonDefinition` namespaces only affects config injections, but it may be a useful feature for collaborating assemblies too.
TyphoonConfigs now work in the following way:
- Global configs (created via plist-integration, app-delegate integration, or using the deprecated methods) are used to inject values in definitions from any assembly,
- Per-assembly configs (created using new -`withConfigName:` family of methods) are used to inject values in definitions from the same assembly.
`TyphoonComponentFactory` holds its …
> Namespacing for TyphoonDefinitions and TyphoonConfigPostProcessors

- Source/Configuration/DefinitionOptionConfiguration/Matcher/TyphoonOptionMatcher.h
- Source/Configuration/DefinitionOptionConfiguration/Matcher/TyphoonOptionMatcher.m
- Tests/Configuration/DefinitionOptionConfiguration/AssemblyWithDefinitionConfiguration.h
- Tests/Configuration/DefinitionOptionConfiguration/AssemblyWithDefinitionConfiguration.m
- Tests/Configuration/DefinitionOptionConfiguration/DefinitionConfigurationTest.m
Related issue https://github.com/appsquickly/Typhoon/issues/454
> Added conformsToProtocol feature for typhoon matcher

- Source/ios/Storyboard/TyphoonViewHelpers.m
- Tests/iOS/Storyboard/TyphoonViewHelpersTests.m
I create NSLayoutConstraint to TyphoonLoadedView and create IBOutlet for him. When controller with this view appeared, I changed the constant of the constraint.
This change did not work, because the outlet pointer does not coincide with any constraint of the TyphoonLoadedView.
I found out that the problem lies in the fact that a copy of NSLayoutConstraint.
I changed a copy on changing the value of the source and destination view and add this сonstraint (the same pointer) in view loaded from Nib.
This solved my problem.
> Fixed problem with external TyphoonLoadedView outlets

- Source/Factory/Internal/NSInvocation+TCFWrapValues.m
- Source/Utils/TyphoonIntrospectionUtils.h
- Source/Utils/TyphoonIntrospectionUtils.m
- Tests/Utils/TyphoonInvocationUtilsTestObjects.h
- Tests/Utils/TyphoonInvocationUtilsTestObjects.m
- Tests/Utils/TyphoonInvocationUtilsTests.m
This MR linked to [issue](https://github.com/appsquickly/Typhoon/issues/493)
Conclusions: 
Function ```[self getArgument:&pointer atIndex:idx];``` into ```- (id)typhoon_getArgumentObjectAtIndex:(NSInteger)idx``` returns NSStackBlock. Stack block cannot simply be retained. If we want retain block, we need to convert NSStackBlock to NSMallocBlock.
In addition, I can write tests for this case if needed :)
> Converting NSStackBlock to NSMallocBlock

- Source/ios/Storyboard/TyphoonViewHelpers.m
- Tests/iOS/Storyboard/TyphoonViewHelpersTests.m
PR for #513
As a result transferring properties was fixed by creating new ```NSLayoutConstraint```
and updated tests for that case
> #513 Transferring constraints from view to view fix

- Source/Configuration/Startup/TyphoonStartup.m
PR solving #508 issue.
As a result, ```+ (void)swizzleSetDelegateMethodOnApplicationClass``` was fixed by changing bundle class.
@alexgarbarev need write tests for this case?
> Fixed bundle resource in setAppDelegate swizzling via Carthage

- Source/ios/Storyboard/NSLayoutConstraint+TyphoonOutletTransfer.h
- Source/ios/Storyboard/NSLayoutConstraint+TyphoonOutletTransfer.m
- Source/ios/Storyboard/TyphoonLoadedView.m
- Source/ios/Storyboard/TyphoonViewHelpers.m
- Source/ios/Storyboard/UIResponder+TyphoonOutletTransfer.h
- Source/ios/Storyboard/UIResponder+TyphoonOutletTransfer.m
- Source/ios/Storyboard/UIView+TyphoonOutletTransfer.h
- Source/ios/Storyboard/UIView+TyphoonOutletTransfer.m
- Tests/iOS/Storyboard/LoadedView.h
- Tests/iOS/Storyboard/LoadedView.m
- Tests/iOS/Storyboard/LoadedView.xib
- Tests/iOS/Storyboard/RootView.h
- Tests/iOS/Storyboard/RootView.m
- Tests/iOS/Storyboard/RootView.xib
- Tests/iOS/Storyboard/RootViewAssembly.h
- Tests/iOS/Storyboard/RootViewAssembly.m
- Tests/iOS/Storyboard/TyphoonLoadedViewTransferOutletTests.m
- Tests/iOS/Storyboard/TyphoonViewHelpersTests.m
- Typhoon.xcodeproj/project.pbxproj
- Typhoon.xcodeproj/xcshareddata/xcschemes/Typhoon.xcscheme
Solution with a subclass does not work ( in the ios 10 no more ivar firstItem, secondItem). 
In the pull request, I implemented another more complicated solution. It works correctly on all operating system versions. I also added integration tests on the transfer of outlets. I hope you are satisfied with this solution, unfortunately more elegant and working solution could not be found. Even with the use swizzle (these solutions also tried).
> Fixed the problem discussed in issues 513

- Source/Factory/Internal/NSInvocation+TCFInstanceBuilder.m
- Source/Factory/Internal/NSInvocation+TCFWrapValues.h
- Source/Factory/Internal/NSInvocation+TCFWrapValues.m
- Tests/Definition/TyphoonInjectionDefinitionTests.m
- Tests/Factory/Assembly/TestAssemblies/MiddleAgesAssembly.h
- Tests/Factory/Assembly/TestAssemblies/MiddleAgesAssembly.m
- Tests/Model/RectModel.h
- Tests/Model/RectModel.m
- Typhoon.xcodeproj/project.pbxproj
This PR solving [issue](https://github.com/appsquickly/Typhoon/issues/456)
As a result, in TCFWrapValues category of NSInvocation was implemented method that returns returnValue of current invocation and wrap primitive value if needed. 
And used for `resultOfInvokingOn:`, because if function `[self getReturnValue:]` returns primitive value, id type is will be wrong.
> #456-Wrapping primitive values NSInvocation

- Source/Factory/TyphoonComponentFactory.h
`TyphoonComponentFactory.attachDefinitionPostProcessor` and `TyphoonComponentFactory.attachInstancePostProcessor` both resolve to `TyphoonComponentFactory.attach` with Swift's automatic method name generation.
This causes a compilation error with Swift 3 (maybe even earlier versions; all I know is that I wasn't encountering this in Swift 1.x): `myAssembly.attach(myPatcher)` would fail saying that method `attach` is ambiguous. Unfortunately, there doesn't seem to be a workaround, so I resorted to `NS_SWIFT_NAME` to explicitly set the Swift method names.
> Fix 'attach' method declarations that are ambiguous in Swift 3

- Source/Factory/Internal/TyphoonBlockComponentFactory.m
In my case, its need for the test that factory is correctly injected and its selectors contains in TyphoonBlockComponentFactory.
If  TyphoonBlockComponentFactory doesn't respondToSelector, try to check that one of the TyphoonDefinition could respondToSelector.
> Changed the logic respondToSelector in TyphoonBlockComponentFactory

- README.md
- Source/Vendor/OCLogTemplate/README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- Source/Configuration/Startup/TyphoonStartup.m
This fixes an issue that setting application delegate with nil or for the second time has no effect.
> Always calls setDelegate: original implementation.

- Source/Definition/Internal/TyphoonBlockDefinitionController.h
- Source/Definition/Internal/TyphoonBlockDefinitionController.m
- Source/Definition/TyphoonBlockDefinition.h
- Source/Factory/Internal/TyphoonCallStack.h
- Source/Factory/Internal/TyphoonCallStack.m
- Tests/Factory/Assembly/TestAssemblies/MiddleAgesAssembly.m
- Tests/Utils/TyphoonInvocationUtilsTestObjects.h
- Tests/Utils/TyphoonInvocationUtilsTestObjects.m
- Tests/Utils/TyphoonInvocationUtilsTests.m
Just changing the warnings this time with no changes to settings, this should now work for all targets without the need to update Xcode's recommended settings…
I did a search through the project and fixed all the ones I could find, hopefully I didn't miss any.
> Fixed "This block declaration is not a prototype" warnings.

- Source/Factory/Pool/TyphoonComponentsPool.h
I tried to build library on Xcode 9.3 beta and received errors:
1) Expected method to read dictionary element not found on object of type 'id<TyphoonComponentsPool>'
2) Expected method to write dictionary element not found on object of type 'id<TyphoonComponentsPool>'
Adding subscript methods solves this problem.
> Add subscript methods to component pool protocol for fix building library on Xcode 9.3

- Source/ios/Configuration/TyphoonViewControllerInjector.m
The UITabBarController's property childViewControllers only contains the visible tabs, when there are more than 4 tabs on a smaller screen a more tab gets created. This screws with the injection and ignores the tabs that are now in the more tab. This pull request tries to fix this issue by instead calling the UITabBarController's viewController property which does contain the other tabs.
> Fix ViewControllerInjector for UITabBarController

- index.html
Fixes the API link on the Typhoon home page. Similar to #594 .
> Fix API link on home page

- Typhoon.xcodeproj/xcshareddata/xcschemes/Typhoon tvOS.xcscheme
- Typhoon.xcodeproj/xcshareddata/xcschemes/Typhoon-iOSTests.xcscheme
- Typhoon.xcodeproj/xcshareddata/xcschemes/Typhoon.xcscheme
Tests targets were built with the frameworks, not sure it was on purpose as it's not the default behaviour.
> Fix Carthage support
